# Generated by Django 5.1.4 on 2025-09-18 20:12

import core.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default=core.enum.AppointmentStatus['PENDING'], max_length=15),
        ),
    ]
